friendsname = input("enter your freinds name?")
print(friendsname)
num1 = int(input("enter num1: "))
num2 = int(input("enter num2: "))
operation = input("Enter the operation +,-,*,/")
print(num1 + num2)
print(num1 - num2)
print(num2 * num1)
print(num2 / num1)
